// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // In Prisma 7, schema is configured via PrismaPg adapter option, not URL parameter
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
